# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170608_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': '\u0424\u043e\u0442\u043e', 'verbose_name_plural': 'a lot of Photo'},
        ),
    ]
